create table
  public.global_inventory (
    id bigint generated by default as identity,
    num_red_potion integer null default 0,
    num_red_ml integer null default 0,
    gold integer null default 100,
    num_green_potion integer null default 0,
    num_green_ml integer null default 0,
    num_blue_potion integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_potion bigint null,
    num_dark_ml bigint null default '0'::bigint,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.potion_catalog (
    id bigint generated by default as identity,
    sku text null default ''::text,
    red bigint null,
    quantity bigint null,
    price bigint null,
    green bigint null default '0'::bigint,
    blue bigint null,
    dark bigint null,
    name text null,
    constraint catalog_pkey primary key (id)
  ) tablespace pg_default;